
export enum ViewState {
  WELCOME = 'WELCOME',
  REGISTER = 'REGISTER',
  SERVER_SETUP = 'SERVER_SETUP',
  AI_GENERATOR = 'AI_GENERATOR'
}

export interface Member {
  id?: number; // Generated by DB
  foto?: string; // Base64 or URL
  nome_completo: string;
  login: string;
  data_nascimento: string;
  estado_civil: string;
  nome_conjuge?: string;
  data_casamento?: string;
  telefone: string;
  email: string;
  cep: string;
  logradouro: string;
  bairro: string;
  cidade: string;
  uf: string;
  possui_veiculo: boolean;
  modelo_veiculo?: string;
  paroquia: string;
  comunidade: string;
  setor: string;
  funcao: string;
  data_ingresso: string;
  observacoes?: string;
}

export interface GeneratedCode {
  title: string;
  code: string;
  explanation: string;
}

export interface ServerMetric {
  label: string;
  value: string;
  status: 'good' | 'warning' | 'error';
}

export type LogType = 'info' | 'success' | 'error' | 'warning';

export interface LogEntry {
  id: string;
  timestamp: Date;
  type: LogType;
  message: string;
  details?: string;
}
