
export enum ViewState {
  WELCOME = 'WELCOME',
  REGISTER = 'REGISTER',
  SERVER_SETUP = 'SERVER_SETUP',
  AI_GENERATOR = 'AI_GENERATOR',
  DASHBOARD = 'DASHBOARD',
  REPORTS = 'REPORTS',
  ELDERS_MODULE = 'ELDERS_MODULE'
}

export interface Member {
  id?: number; // Generated by DB
  foto?: string; // Base64 or URL
  nome_completo: string;
  login: string;
  data_nascimento: string;
  estado_civil: string;
  nome_conjuge?: string;
  data_casamento?: string;
  telefone: string;
  email: string;
  cep: string;
  logradouro: string;
  bairro: string;
  cidade: string;
  uf: string;
  possui_veiculo: boolean;
  modelo_veiculo?: string;
  paroquia: string;
  comunidade: string;
  setor: string;
  funcao: string;
  data_ingresso: string;
  observacoes?: string;
}

export interface Assistido {
  id?: number;
  foto?: string; // Base64
  nome_completo: string;
  data_nascimento?: string;
  responsavel_nome?: string;
  telefone_principal: string;
  telefone_responsavel?: string;
  endereco_logradouro: string;
  endereco_numero: string;
  endereco_bairro: string;
  endereco_cidade: string;
  endereco_cep: string;
  ponto_referencia?: string;
  necessidades_especiais?: string;
  usa_cadeira_rodas: boolean;
  ativo: boolean;
}

export interface Evento {
  id?: number;
  titulo: string;
  descricao?: string;
  data_inicio: string; // ISO datetime
  local_nome: string;
  local_endereco: string;
  ativo: boolean;
}

export interface Escala {
  id?: number;
  evento_id: number;
  motorista_id: number; // Link to Member
  assistido_id: number; // Link to Assistido
  status: 'Planejada' | 'Confirmada' | 'Concluida' | 'Cancelada';
  tipo: 'Ida' | 'Volta' | 'Ambos';
}

export interface GeneratedCode {
  title: string;
  code: string;
  explanation: string;
}

export interface ServerMetric {
  label: string;
  value: string;
  status: 'good' | 'warning' | 'error';
}

export type LogType = 'info' | 'success' | 'error' | 'warning';

export interface LogEntry {
  id: string;
  timestamp: Date;
  type: LogType;
  message: string;
  details?: string;
}