export enum ViewState {
  WELCOME = 'WELCOME',
  REGISTER = 'REGISTER',
  SERVER_SETUP = 'SERVER_SETUP'
}

export interface Member {
  id?: number; // Generated by DB
  foto?: string; // Base64 or URL
  nome_completo: string;
  login: string;
  data_nascimento: string;
  estado_civil: string;
  nome_conjuge?: string;
  data_casamento?: string;
  telefone: string;
  email: string;
  cep: string;
  logradouro: string;
  bairro: string;
  cidade: string;
  uf: string;
  possui_veiculo: boolean;
  modelo_veiculo?: string;
  paroquia: string;
  comunidade: string;
  setor: string;
  funcao: string;
  data_ingresso: string;
  observacoes?: string;
}

// Added to fix error in services/geminiService.ts and components/ApiGenerator.tsx
export interface GeneratedCode {
  title: string;
  code: string;
  explanation: string;
}

// Added to fix error in components/Dashboard.tsx
export interface ServerMetric {
  label: string;
  value: string;
  status: 'good' | 'warning' | 'error';
}