
import React, { useState } from 'react';
import { LogType } from '../types';

interface ServerSetupProps {
  onBack: () => void;
  onNavigateToAI: () => void;
  addLog: (type: LogType, message: string, details?: string) => void;
  serverUrl: string;
  onUpdateServerUrl: (newUrl: string) => void;
}

export const ServerSetup: React.FC<ServerSetupProps> = ({ onBack, onNavigateToAI, addLog, serverUrl, onUpdateServerUrl }) => {
  const [activeTab, setActiveTab] = useState<'node' | 'sql' | 'guide' | 'ngrok'>('guide');
  const [copied, setCopied] = useState(false);
  const [testing, setTesting] = useState(false);
  const [isEditingUrl, setIsEditingUrl] = useState(false);
  const [tempUrl, setTempUrl] = useState(serverUrl);

  const isHttps = window.location.protocol === 'https:';
  const targetIsHttp = tempUrl.startsWith('http:');
  const showMixedContentWarning = isHttps && targetIsHttp;

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleTestConnection = async () => {
      setTesting(true);
      const urlToTest = serverUrl.replace(/\/$/, ''); // Remove trailing slash
      addLog('info', 'Tentando conectar ao backend...', `GET ${urlToTest}/`);
      
      try {
          const controller = new AbortController();
          const timeoutId = setTimeout(() => controller.abort(), 8000); // 8s timeout
          
          const response = await fetch(`${urlToTest}/`, { 
              signal: controller.signal,
              mode: 'cors',
              headers: {
                  'Content-Type': 'application/json',
                  'ngrok-skip-browser-warning': 'true', // Bypass Ngrok page
                  'Bypass-Tunnel-Reminder': 'true'
              }
          });
          clearTimeout(timeoutId);

          const text = await response.text();
          
          // Log raw response for debugging
          addLog(response.ok ? 'success' : 'error', `Status: ${response.status}`, `Body: ${text.substring(0, 200)}`);
          
          if (response.ok) {
              if (text.trim().startsWith('<!DOCTYPE html>') || text.includes('ngrok-free.dev')) {
                  addLog('warning', 'Bloqueio Ngrok Detectado', 'O link funciona, mas retornou a tela de aviso do Ngrok. Atualize o server.js para aceitar headers de bypass.');
                  alert("Conexão parcial! O Ngrok exibiu uma tela de aviso.\nAtualize o 'server.js' (Aba 3) para corrigir.");
              } else {
                  alert("Sucesso! Conexão estabelecida com o servidor.");
              }
          } else {
               alert(`O servidor respondeu com erro: ${response.status}`);
          }
      } catch (error) {
           const err = error instanceof Error ? error.message : String(error);
           if (err.includes('aborted')) {
               addLog('error', 'Timeout', `O servidor não respondeu em 8s. Verifique IP e Firewall.`);
           } else if (err.includes('Failed to fetch')) {
               addLog('error', 'Falha de Rede/CORS', `Não foi possível conectar. Verifique se o server.js permite CORS e se o endereço está correto.`);
           } else {
               addLog('error', 'Erro de Conexão', err);
           }
      } finally {
          setTesting(false);
      }
  };

  const handleSaveUrl = () => {
      onUpdateServerUrl(tempUrl);
      setIsEditingUrl(false);
  };

  const sqlCode = `
-- 1. Criação da Tabela 'membros'
CREATE TABLE IF NOT EXISTS membros (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  foto TEXT,
  nome_completo TEXT NOT NULL,
  login TEXT NOT NULL UNIQUE,
  data_nascimento DATE NOT NULL,
  estado_civil TEXT NOT NULL,
  nome_conjuge TEXT,
  data_casamento DATE,
  telefone TEXT NOT NULL,
  email TEXT NOT NULL,
  cep TEXT NOT NULL,
  logradouro TEXT NOT NULL,
  bairro TEXT NOT NULL,
  cidade TEXT NOT NULL,
  uf TEXT NOT NULL,
  possui_veiculo BOOLEAN NOT NULL DEFAULT false,
  modelo_veiculo TEXT,
  paroquia TEXT NOT NULL,
  comunidade TEXT NOT NULL,
  setor TEXT NOT NULL,
  funcao TEXT NOT NULL,
  data_ingresso DATE NOT NULL DEFAULT CURRENT_DATE,
  observacoes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. Tabela de Assistidos (Idosos)
CREATE TABLE IF NOT EXISTS assistidos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  foto TEXT,
  nome_completo TEXT NOT NULL,
  data_nascimento DATE,
  responsavel_nome TEXT,
  telefone_principal TEXT NOT NULL,
  telefone_responsavel TEXT,
  endereco_logradouro TEXT,
  endereco_numero TEXT,
  endereco_bairro TEXT,
  endereco_cidade TEXT,
  endereco_cep TEXT,
  ponto_referencia TEXT,
  necessidades_especiais TEXT,
  usa_cadeira_rodas BOOLEAN DEFAULT false,
  ativo BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. Tabela de Eventos (Missas)
CREATE TABLE IF NOT EXISTS eventos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo TEXT DEFAULT 'Missa da Saúde',
  descricao TEXT,
  data_inicio TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  local_nome TEXT,
  local_endereco TEXT,
  ativo BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 4. Tabela de Escalas (Transporte)
CREATE TABLE IF NOT EXISTS escalas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  evento_id BIGINT REFERENCES eventos(id) ON DELETE CASCADE,
  motorista_id BIGINT REFERENCES membros(id) ON DELETE SET NULL,
  assistido_id BIGINT REFERENCES assistidos(id) ON DELETE CASCADE,
  status TEXT DEFAULT 'Planejada', -- Planejada, Confirmada, Concluida, Cancelada
  tipo TEXT DEFAULT 'Ambos', -- Ida, Volta, Ambos
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  UNIQUE(evento_id, assistido_id)
);

-- 5. STORED PROCEDURE: Duplicar Evento e Escalas
CREATE OR REPLACE FUNCTION duplicate_event(p_original_id BIGINT, p_new_date TIMESTAMP)
RETURNS BIGINT AS $$
DECLARE
  v_new_id BIGINT;
BEGIN
  -- Copia o evento, define nova data e marca como Inativo
  INSERT INTO eventos (titulo, descricao, data_inicio, local_nome, local_endereco, ativo)
  SELECT titulo, descricao, p_new_date, local_nome, local_endereco, false
  FROM eventos WHERE id = p_original_id
  RETURNING id INTO v_new_id;

  -- Copia as escalas do evento original para o novo, resetando status para Planejada
  INSERT INTO escalas (evento_id, motorista_id, assistido_id, status, tipo)
  SELECT v_new_id, motorista_id, assistido_id, 'Planejada', tipo
  FROM escalas WHERE evento_id = p_original_id;

  RETURN v_new_id;
END;
$$ LANGUAGE plpgsql;
`;

  const nodeCode = `
// server.js - Versão 13 (Com Login Motorista & Duplicação)
// Instale: npm install express pg dotenv cors

require('dotenv').config();
const express = require('express');
const { Pool } = require('pg');
const cors = require('cors');

const app = express();
const port = process.env.PORT || 3000;

app.use((req, res, next) => {
  res.header("Access-Control-Allow-Origin", "*"); 
  res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept, Authorization, ngrok-skip-browser-warning, Bypass-Tunnel-Reminder, Access-Control-Allow-Private-Network");
  res.header("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS");
  res.header("Access-Control-Allow-Private-Network", "true");
  if (req.method === 'OPTIONS') return res.sendStatus(200);
  next();
});

app.use(express.json({ limit: '50mb' }));
app.use(express.urlencoded({ limit: '50mb', extended: true }));

const pool = new Pool({
  user: process.env.DB_USER || 'postgres',
  host: process.env.DB_HOST || 'localhost',
  database: process.env.DB_NAME || 'pastoral_db',
  password: process.env.DB_PASSWORD || 'sua_senha_aqui',
  port: process.env.DB_PORT || 5432,
});

pool.connect((err) => {
  if (err) console.error('❌ Erro Fatal DB:', err.message);
  else console.log('✅ Conectado ao PostgreSQL!');
});

app.get('/', (req, res) => res.json({ message: 'API Pastoral Online ✝️', status: 'Running' }));

// --- ROTAS MEMBROS ---
app.get('/api/membros', async (req, res) => {
  const r = await pool.query('SELECT * FROM membros ORDER BY created_at DESC');
  res.json(r.rows);
});
app.post('/api/membros', async (req, res) => {
    try {
        const d = req.body;
        await pool.query(
            \`INSERT INTO membros (foto, nome_completo, login, data_nascimento, estado_civil, nome_conjuge, data_casamento, telefone, email, cep, logradouro, bairro, cidade, uf, possui_veiculo, modelo_veiculo, paroquia, comunidade, setor, funcao, data_ingresso, observacoes) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22)\`,
            [d.foto, d.nome_completo, d.login, d.data_nascimento, d.estado_civil, d.nome_conjuge, d.data_casamento, d.telefone, d.email, d.cep, d.logradouro, d.bairro, d.cidade, d.uf, d.possui_veiculo, d.modelo_veiculo, d.paroquia, d.comunidade, d.setor, d.funcao, d.data_ingresso, d.observacoes]
        );
        res.status(201).json({success: true});
    } catch (e) { res.status(500).json({error: e.message}); }
});
app.put('/api/membros/:id', async (req, res) => {
    try {
        const d = req.body;
        await pool.query(
            \`UPDATE membros SET foto=$1, nome_completo=$2, login=$3, data_nascimento=$4, estado_civil=$5, nome_conjuge=$6, data_casamento=$7, telefone=$8, email=$9, cep=$10, logradouro=$11, bairro=$12, cidade=$13, uf=$14, possui_veiculo=$15, modelo_veiculo=$16, paroquia=$17, comunidade=$18, setor=$19, funcao=$20, data_ingresso=$21, observacoes=$22 WHERE id=$23\`,
            [d.foto, d.nome_completo, d.login, d.data_nascimento, d.estado_civil, d.nome_conjuge, d.data_casamento, d.telefone, d.email, d.cep, d.logradouro, d.bairro, d.cidade, d.uf, d.possui_veiculo, d.modelo_veiculo, d.paroquia, d.comunidade, d.setor, d.funcao, d.data_ingresso, d.observacoes, req.params.id]
        );
        res.json({success: true});
    } catch (e) { res.status(500).json({error: e.message}); }
});
app.delete('/api/membros/:id', async (req, res) => {
    try { await pool.query('DELETE FROM membros WHERE id=$1', [req.params.id]); res.json({success: true}); } catch (e) { res.status(500).json({error: e.message}); }
});
app.post('/api/membros/check-login', async (req, res) => {
  // ATENÇÃO: Incluído 'possui_veiculo' para o módulo de transporte
  const r = await pool.query('SELECT id, funcao, nome_completo, estado_civil, data_nascimento, data_casamento, possui_veiculo FROM membros WHERE UPPER(login) = UPPER($1)', [req.body.login]);
  res.json(r.rows.length > 0 ? { found: true, ...r.rows[0] } : { found: false });
});

// --- ROTAS MÓDULO IDOSOS ---

// 1. Assistidos
app.get('/api/assistidos', async (req, res) => {
  try {
    const r = await pool.query('SELECT * FROM assistidos ORDER BY nome_completo ASC');
    res.json(r.rows);
  } catch (e) { res.status(500).json({error: e.message}); }
});

app.post('/api/assistidos', async (req, res) => {
  try {
    const d = req.body;
    const r = await pool.query(
      \`INSERT INTO assistidos (foto, nome_completo, data_nascimento, responsavel_nome, telefone_principal, telefone_responsavel, endereco_logradouro, endereco_numero, endereco_bairro, endereco_cidade, endereco_cep, ponto_referencia, necessidades_especiais, usa_cadeira_rodas, ativo) 
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15) RETURNING id\`,
      [d.foto, d.nome_completo, d.data_nascimento, d.responsavel_nome, d.telefone_principal, d.telefone_responsavel, d.endereco_logradouro, d.endereco_numero, d.endereco_bairro, d.endereco_cidade, d.endereco_cep, d.ponto_referencia, d.necessidades_especiais, d.usa_cadeira_rodas, d.ativo]
    );
    res.status(201).json({id: r.rows[0].id});
  } catch (e) { res.status(500).json({error: e.message}); }
});

app.put('/api/assistidos/:id', async (req, res) => {
  try {
    const d = req.body;
    await pool.query(
      \`UPDATE assistidos SET foto=$1, nome_completo=$2, data_nascimento=$3, responsavel_nome=$4, telefone_principal=$5, telefone_responsavel=$6, endereco_logradouro=$7, endereco_numero=$8, endereco_bairro=$9, endereco_cidade=$10, endereco_cep=$11, ponto_referencia=$12, necessidades_especiais=$13, usa_cadeira_rodas=$14, ativo=$15 WHERE id=$16\`,
      [d.foto, d.nome_completo, d.data_nascimento, d.responsavel_nome, d.telefone_principal, d.telefone_responsavel, d.endereco_logradouro, d.endereco_numero, d.endereco_bairro, d.endereco_cidade, d.endereco_cep, d.ponto_referencia, d.necessidades_especiais, d.usa_cadeira_rodas, d.ativo, req.params.id]
    );
    res.json({success: true});
  } catch (e) { res.status(500).json({error: e.message}); }
});

app.delete('/api/assistidos/:id', async (req, res) => {
  try { await pool.query('DELETE FROM assistidos WHERE id=$1', [req.params.id]); res.json({success: true}); } 
  catch (e) { res.status(500).json({error: e.message}); }
});

// 2. Eventos
app.get('/api/eventos', async (req, res) => {
  try {
    const r = await pool.query('SELECT * FROM eventos ORDER BY data_inicio DESC');
    res.json(r.rows);
  } catch (e) { res.status(500).json({error: e.message}); }
});

app.post('/api/eventos', async (req, res) => {
  try {
    const d = req.body;
    const r = await pool.query(
      \`INSERT INTO eventos (titulo, descricao, data_inicio, local_nome, local_endereco, ativo) VALUES ($1, $2, $3, $4, $5, $6) RETURNING id\`,
      [d.titulo, d.descricao, d.data_inicio, d.local_nome, d.local_endereco, d.ativo]
    );
    res.status(201).json({id: r.rows[0].id});
  } catch (e) { res.status(500).json({error: e.message}); }
});

app.put('/api/eventos/:id', async (req, res) => {
  try {
    const d = req.body;
    await pool.query(
      \`UPDATE eventos SET titulo=$1, descricao=$2, data_inicio=$3, local_nome=$4, local_endereco=$5, ativo=$6 WHERE id=$7\`,
      [d.titulo, d.descricao, d.data_inicio, d.local_nome, d.local_endereco, d.ativo, req.params.id]
    );
    res.json({success: true});
  } catch (e) { res.status(500).json({error: e.message}); }
});

app.delete('/api/eventos/:id', async (req, res) => {
  try { await pool.query('DELETE FROM eventos WHERE id=$1', [req.params.id]); res.json({success: true}); } 
  catch (e) { res.status(500).json({error: e.message}); }
});

app.post('/api/eventos/:id/duplicate', async (req, res) => {
  try {
    const { new_date } = req.body;
    if (!new_date) throw new Error('Nova data é obrigatória');
    
    // Chama a Stored Procedure criada no SQL
    const r = await pool.query('SELECT duplicate_event($1, $2) as new_id', [req.params.id, new_date]);
    
    res.json({ success: true, new_id: r.rows[0].new_id });
  } catch (e) { res.status(500).json({ error: e.message }); }
});

// 3. Escalas
app.get('/api/escalas/:evento_id', async (req, res) => {
  try {
    const r = await pool.query('SELECT * FROM escalas WHERE evento_id = $1', [req.params.evento_id]);
    res.json(r.rows);
  } catch (e) { res.status(500).json({error: e.message}); }
});

app.post('/api/escalas/batch', async (req, res) => {
  const client = await pool.connect();
  try {
    await client.query('BEGIN');
    const { evento_id, escalas } = req.body;
    
    // Limpa escalas anteriores deste evento (Reset)
    await client.query('DELETE FROM escalas WHERE evento_id = $1', [evento_id]);
    
    // Insere novas
    for (const escala of escalas) {
      await client.query(
        'INSERT INTO escalas (evento_id, motorista_id, assistido_id, status, tipo) VALUES ($1, $2, $3, $4, $5)',
        [evento_id, escala.motorista_id, escala.assistido_id, escala.status || 'Planejada', escala.tipo || 'Ambos']
      );
    }
    await client.query('COMMIT');
    res.json({success: true});
  } catch (e) {
    await client.query('ROLLBACK');
    res.status(500).json({error: e.message});
  } finally {
    client.release();
  }
});

app.listen(port, '0.0.0.0', () => console.log(\`🚀 Server running on port \${port}\`));
`;

  return (
    <div className="p-6 h-full flex flex-col text-slate-100 animate-fade-in">
       {/* Header */}
       <div className="flex items-center justify-between mb-6">
        <div className="flex items-center gap-4">
          <button onClick={onBack} className="p-2 rounded-full bg-white/10 hover:bg-white/20 backdrop-blur text-white transition-all">
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15 19l-7-7 7-7" /></svg>
          </button>
          <h2 className="text-xl font-bold">Configuração do Servidor</h2>
        </div>
        <button 
           onClick={onNavigateToAI}
           className="text-xs text-blue-300 hover:text-white underline"
        >
          Precisa customizar?
        </button>
      </div>

      {/* Server Config Bar */}
      <div className="bg-blue-900/30 border border-blue-500/30 rounded-xl p-4 mb-6 flex flex-col gap-4">
        
        {showMixedContentWarning && (
            <div className="bg-orange-500/20 border border-orange-500/50 p-3 rounded text-orange-200 text-xs flex items-start gap-2">
                <svg className="w-5 h-5 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" /></svg>
                <div>
                    <strong>Atenção (Mixed Content):</strong> O navegador pode bloquear conexões HTTPS para HTTP local.
                    <br/>Solução: Use o Ngrok (aba 4) para criar um túnel seguro (https).
                </div>
            </div>
        )}

        <div className="flex flex-col md:flex-row items-center gap-4">
            <div className="flex items-center gap-3 w-full md:w-auto">
                <div className="p-2 bg-blue-500/20 rounded-full">
                    <svg className="w-5 h-5 text-blue-300" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 12h14M5 12a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v4a2 2 0 01-2 2M5 12a2 2 0 01-2 2v4a2 2 0 012 2h14a2 2 0 012-2v-4a2 2 0 01-2-2m-2-4h.01M17 16h.01" /></svg>
                </div>
                <div className="flex-1">
                    <label className="text-[10px] text-blue-300 uppercase font-bold tracking-wider block">Endereço do Servidor (API)</label>
                    {isEditingUrl ? (
                        <div className="flex items-center gap-2 mt-1">
                            <input 
                                type="text" 
                                value={tempUrl} 
                                onChange={(e) => setTempUrl(e.target.value)} 
                                className="bg-black/40 border border-blue-400 rounded px-2 py-1 text-sm text-white focus:outline-none w-full md:w-64"
                            />
                            <button onClick={handleSaveUrl} className="text-xs bg-green-600 hover:bg-green-500 text-white px-2 py-1 rounded">Salvar</button>
                            <button onClick={() => { setTempUrl(serverUrl); setIsEditingUrl(false); }} className="text-xs bg-slate-700 hover:bg-slate-600 text-white px-2 py-1 rounded">Cancelar</button>
                        </div>
                    ) : (
                        <div className="flex items-center gap-2 mt-1">
                            <span className="font-mono text-lg font-bold text-white">{serverUrl}</span>
                            <button onClick={() => setIsEditingUrl(true)} className="text-xs text-slate-400 hover:text-white" title="Editar IP">
                                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" /></svg>
                            </button>
                        </div>
                    )}
                </div>
            </div>
            
            <div className="h-8 w-[1px] bg-white/10 hidden md:block" />

            <div className="flex-1 w-full md:w-auto flex justify-end">
                <button 
                    onClick={handleTestConnection}
                    disabled={testing}
                    className={`w-full md:w-auto text-sm px-4 py-2 rounded-lg border transition-all flex items-center justify-center gap-2 font-semibold shadow-lg ${testing ? 'bg-yellow-500/20 border-yellow-500 text-yellow-200' : 'bg-green-500 hover:bg-green-400 text-white border-green-500/50'}`}
                >
                    {testing ? (
                        <>
                            <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-yellow-200"></div>
                            Verificando...
                        </>
                    ) : (
                        <>
                            Testar Conexão
                            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7" /></svg>
                        </>
                    )}
                </button>
            </div>
        </div>
    </div>

      {/* Tabs */}
      <div className="flex gap-2 mb-4 overflow-x-auto pb-2 md:pb-0">
        <button 
          onClick={() => setActiveTab('guide')}
          className={`flex-1 min-w-[120px] py-3 rounded-lg text-sm font-semibold transition-colors ${activeTab === 'guide' ? 'bg-indigo-600 text-white shadow-lg shadow-indigo-900/20' : 'bg-white/5 text-slate-400 hover:bg-white/10'}`}
        >
          1. Passo a Passo
        </button>
        <button 
          onClick={() => setActiveTab('sql')}
          className={`flex-1 min-w-[120px] py-3 rounded-lg text-sm font-semibold transition-colors ${activeTab === 'sql' ? 'bg-blue-600 text-white shadow-lg shadow-blue-900/20' : 'bg-white/5 text-slate-400 hover:bg-white/10'}`}
        >
          2. SQL Tabela
        </button>
        <button 
          onClick={() => setActiveTab('node')}
          className={`flex-1 min-w-[120px] py-3 rounded-lg text-sm font-semibold transition-colors ${activeTab === 'node' ? 'bg-green-600 text-white shadow-lg shadow-green-900/20' : 'bg-white/5 text-slate-400 hover:bg-white/10'}`}
        >
          3. Node.js API
        </button>
        <button 
          onClick={() => setActiveTab('ngrok')}
          className={`flex-1 min-w-[120px] py-3 rounded-lg text-sm font-semibold transition-colors ${activeTab === 'ngrok' ? 'bg-orange-600 text-white shadow-lg shadow-orange-900/20' : 'bg-white/5 text-slate-400 hover:bg-white/10'}`}
        >
          4. Ngrok (Vercel)
        </button>
      </div>

      {/* Code Area */}
      <div className="flex-1 relative bg-[#0d1117] rounded-xl border border-white/10 overflow-hidden flex flex-col shadow-inner">
        {activeTab === 'node' || activeTab === 'sql' ? (
            <div className="absolute top-0 right-0 p-3 z-10">
            <button 
                onClick={() => copyToClipboard(activeTab === 'node' ? nodeCode : sqlCode)}
                className="px-3 py-1.5 bg-white/10 hover:bg-white/20 rounded text-xs text-white border border-white/10 backdrop-blur transition-all active:scale-95 flex items-center gap-2"
            >
                {copied ? (
                    <>
                    <svg className="w-3 h-3 text-green-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7" /></svg>
                    Copiado!
                    </>
                ) : (
                    <>
                    <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M8 5H6a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2v-1M8 5a2 2 0 002 2h2a2 2 0 002-2M8 5a2 2 0 012-2h2a2 2 0 012 2m0 0h2a2 2 0 012 2v3m2 4H10m0 0l3-3m-3 3l3 3" /></svg>
                    Copiar
                    </>
                )}
            </button>
            </div>
        ) : null}
        
        <div className="flex-1 overflow-auto custom-scrollbar p-6">
            {activeTab === 'guide' && (
                <div className="space-y-8 text-sm text-slate-300">
                    
                    {/* TROUBLESHOOTING SECTION */}
                    <div className="bg-red-900/10 border border-red-500/20 p-4 rounded-lg">
                        <h3 className="text-red-300 font-bold text-lg mb-2 flex items-center gap-2">
                           ⚠️ IMPORTANTE: Atualização para Módulo Idosos
                        </h3>
                        <p className="mb-2">Para habilitar o módulo "Missa da Saúde", você precisa rodar os scripts SQL e atualizar o Node.js.</p>
                        <ol className="list-decimal pl-5 space-y-2 text-white">
                            <li>Vá para a aba <strong className="text-blue-300">2. SQL Tabela</strong> e rode o script no seu PGAdmin/DBeaver.</li>
                            <li>Vá para a aba <strong className="text-green-300">3. Node.js API</strong>, copie o código e substitua no seu arquivo <code className="text-green-300">server.js</code>.</li>
                            <li>Reinicie o servidor (<code className="text-green-300">Ctrl+C</code> e depois <code className="text-green-300">node server.js</code>).</li>
                        </ol>
                    </div>

                    <div className="space-y-3">
                        <h3 className="text-blue-300 font-bold text-lg border-b border-white/10 pb-1">Passo A: Descobrir seu IP Real</h3>
                        <p>No terminal do Windows:</p>
                        <code className="block bg-black/40 p-3 rounded border border-white/5 font-mono text-green-400">
                            ipconfig
                        </code>
                        <p>Copie o <strong>IPv4</strong> e cole no campo acima (se não for usar Ngrok).</p>
                    </div>
                </div>
            )}

            {activeTab === 'ngrok' && (
                <div className="space-y-6 text-sm text-slate-300">
                     <div className="bg-orange-900/20 border border-orange-500/20 p-4 rounded-lg">
                        <h3 className="text-orange-300 font-bold text-lg mb-2">Solução Definitiva (Ngrok)</h3>
                        <p>Use o Ngrok para criar um endereço HTTPS seguro para seu servidor local. Isso resolve erros de "Mixed Content" e bloqueios do Vercel.</p>
                    </div>

                    <ol className="list-decimal pl-5 space-y-4">
                        <li>
                            Baixe o Ngrok em <a href="https://ngrok.com/download" target="_blank" className="text-blue-400 underline">ngrok.com</a> e instale.
                        </li>
                        <li>
                            No terminal, inicie o túnel:
                            <code className="block bg-black/40 p-3 rounded border border-white/5 font-mono text-green-400 mt-2">
                                ngrok http 3000
                            </code>
                        </li>
                        <li>
                            Copie o link <code className="text-white">https://....ngrok-free.app</code> e cole no campo "Endereço do Servidor" no topo desta tela.
                        </li>
                    </ol>
                </div>
            )}

            {activeTab === 'node' && (
                <pre className="text-xs md:text-sm font-mono text-blue-100 leading-relaxed">
                    <code>{nodeCode}</code>
                </pre>
            )}

            {activeTab === 'sql' && (
                <pre className="text-xs md:text-sm font-mono text-blue-100 leading-relaxed">
                    <code>{sqlCode}</code>
                </pre>
            )}
        </div>
      </div>
    </div>
  );
};
