
import React, { useState } from 'react';
import { LogType } from '../types';

interface ServerSetupProps {
  onBack: () => void;
  onNavigateToAI: () => void;
  addLog: (type: LogType, message: string, details?: string) => void;
  serverUrl: string;
  onUpdateServerUrl: (newUrl: string) => void;
}

export const ServerSetup: React.FC<ServerSetupProps> = ({ onBack, onNavigateToAI, addLog, serverUrl, onUpdateServerUrl }) => {
  const [activeTab, setActiveTab] = useState<'node' | 'sql' | 'guide' | 'ngrok'>('guide');
  const [copied, setCopied] = useState(false);
  const [testing, setTesting] = useState(false);
  const [isEditingUrl, setIsEditingUrl] = useState(false);
  const [tempUrl, setTempUrl] = useState(serverUrl);

  const isHttps = window.location.protocol === 'https:';
  const targetIsHttp = tempUrl.startsWith('http:');
  const showMixedContentWarning = isHttps && targetIsHttp;

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleTestConnection = async () => {
      setTesting(true);
      const urlToTest = serverUrl.replace(/\/$/, ''); // Remove trailing slash
      addLog('info', 'Tentando conectar ao backend...', `GET ${urlToTest}/`);
      
      try {
          const controller = new AbortController();
          const timeoutId = setTimeout(() => controller.abort(), 8000); // 8s timeout
          
          const response = await fetch(`${urlToTest}/`, { 
              signal: controller.signal,
              mode: 'cors',
              headers: {
                  'Content-Type': 'application/json',
                  'ngrok-skip-browser-warning': 'true', // Bypass Ngrok page
                  'Bypass-Tunnel-Reminder': 'true'
              }
          });
          clearTimeout(timeoutId);

          const text = await response.text();
          
          // Log raw response for debugging
          addLog(response.ok ? 'success' : 'error', `Status: ${response.status}`, `Body: ${text.substring(0, 200)}`);
          
          if (response.ok) {
              if (text.trim().startsWith('<!DOCTYPE html>') || text.includes('ngrok-free.dev')) {
                  addLog('warning', 'Bloqueio Ngrok Detectado', 'O link funciona, mas retornou a tela de aviso do Ngrok. Atualize o server.js para aceitar headers de bypass.');
                  alert("Conexão parcial! O Ngrok exibiu uma tela de aviso.\nAtualize o 'server.js' (Aba 3) para corrigir.");
              } else {
                  alert("Sucesso! Conexão estabelecida com o servidor.");
              }
          } else {
               alert(`O servidor respondeu com erro: ${response.status}`);
          }
      } catch (error) {
           const err = error instanceof Error ? error.message : String(error);
           if (err.includes('aborted')) {
               addLog('error', 'Timeout', `O servidor não respondeu em 8s. Verifique IP e Firewall.`);
           } else if (err.includes('Failed to fetch')) {
               addLog('error', 'Falha de Rede/CORS', `Não foi possível conectar. Verifique se o server.js permite CORS e se o endereço está correto.`);
           } else {
               addLog('error', 'Erro de Conexão', err);
           }
      } finally {
          setTesting(false);
      }
  };

  const handleSaveUrl = () => {
      onUpdateServerUrl(tempUrl);
      setIsEditingUrl(false);
  };

  const sqlCode = `
-- 1. Criação da Tabela 'membros'
CREATE TABLE IF NOT EXISTS membros (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  foto TEXT,
  nome_completo TEXT NOT NULL,
  login TEXT NOT NULL UNIQUE,
  data_nascimento DATE NOT NULL,
  estado_civil TEXT NOT NULL,
  nome_conjuge TEXT,
  data_casamento DATE,
  telefone TEXT NOT NULL,
  email TEXT NOT NULL,
  cep TEXT NOT NULL,
  logradouro TEXT NOT NULL,
  bairro TEXT NOT NULL,
  cidade TEXT NOT NULL,
  uf TEXT NOT NULL,
  possui_veiculo BOOLEAN NOT NULL DEFAULT false,
  modelo_veiculo TEXT,
  paroquia TEXT NOT NULL,
  comunidade TEXT NOT NULL,
  setor TEXT NOT NULL,
  funcao TEXT NOT NULL,
  data_ingresso DATE NOT NULL DEFAULT CURRENT_DATE,
  observacoes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
`;

  const nodeCode = `
// server.js - Versão 8 (Com RBAC Login)
// Instale: npm install express pg dotenv

require('dotenv').config();
const express = require('express');
const { Pool } = require('pg');

const app = express();
const port = process.env.PORT || 3000;

// Configuração de CORS Manual (Mais permissiva para dev)
app.use((req, res, next) => {
  // Permite qualquer origem (Frontend/Vercel)
  res.header("Access-Control-Allow-Origin", "*"); 
  
  // Headers permitidos (IMPORTANTE: ngrok-skip-browser-warning)
  res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept, Authorization, ngrok-skip-browser-warning, Bypass-Tunnel-Reminder, Access-Control-Allow-Private-Network");
  
  // Métodos permitidos
  res.header("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS");
  
  // Permite acesso de rede privada (Localhost -> Chrome)
  res.header("Access-Control-Allow-Private-Network", "true");

  // Responde imediatamente ao Preflight (OPTIONS)
  if (req.method === 'OPTIONS') {
    return res.sendStatus(200);
  }
  next();
});

// Aumenta limite para upload de fotos (base64)
app.use(express.json({ limit: '50mb' }));

// Configuração do Banco de Dados
const pool = new Pool({
  user: process.env.DB_USER || 'postgres',
  host: process.env.DB_HOST || 'localhost',
  database: process.env.DB_NAME || 'pastoral_db',
  password: process.env.DB_PASSWORD || 'sua_senha_aqui',
  port: process.env.DB_PORT || 5432,
});

// Teste de conexão ao iniciar
pool.connect((err, client, release) => {
  if (err) {
    console.error('❌ Erro Fatal ao conectar no PostgreSQL:', err.message);
  } else {
    console.log('✅ Conectado ao PostgreSQL com sucesso!');
    release();
  }
});

// Rota Raiz (Health Check)
app.get('/', (req, res) => {
  console.log('Ping recebido!');
  res.json({ message: 'API Pastoral Online ✝️', status: 'Running' });
});

// --- ROTAS ---

// 1. Verificar Login (Para o Desafio)
app.post('/api/membros/check-login', async (req, res) => {
  console.log('👉 Check Login:', req.body.login);
  let client;
  try {
    client = await pool.connect();
    const { login } = req.body;
    
    // Busca Case Insensitive
    // ATUALIZADO V8: Retorna ID e Função para controle de acesso
    const result = await client.query(
      'SELECT id, funcao, nome_completo, estado_civil, data_nascimento, data_casamento FROM membros WHERE UPPER(login) = UPPER($1)', 
      [login]
    );
    
    if (result.rows.length > 0) {
      console.log('   ✅ Usuário encontrado:', result.rows[0].nome_completo);
      res.json({ found: true, ...result.rows[0] });
    } else {
      console.log('   ❌ Usuário não encontrado');
      res.json({ found: false });
    }
  } catch (err) {
    console.error('❌ Erro no Login:', err);
    res.status(500).json({ error: 'Erro no servidor', details: err.message });
  } finally {
    if (client) client.release();
  }
});

// 2. Listar Todos (GET)
app.get('/api/membros', async (req, res) => {
  console.log('👉 Listando membros...');
  let client;
  try {
    client = await pool.connect();
    const result = await client.query('SELECT * FROM membros ORDER BY created_at DESC');
    console.log(\`   Retornando \${result.rows.length} registros.\`);
    res.json(result.rows);
  } catch (err) {
    console.error('❌ Erro ao listar:', err);
    res.status(500).json({ error: 'Erro ao buscar dados', details: err.message });
  } finally {
    if (client) client.release();
  }
});

// 3. Criar Novo (POST)
app.post('/api/membros', async (req, res) => {
  console.log('👉 Novo Cadastro recebido');
  let client;
  try {
    client = await pool.connect();
    const data = req.body;
    
    const query = \`
      INSERT INTO membros (
        foto, nome_completo, login, data_nascimento, estado_civil,
        nome_conjuge, data_casamento, telefone, email, cep,
        logradouro, bairro, cidade, uf, possui_veiculo,
        modelo_veiculo, paroquia, comunidade, setor, funcao,
        data_ingresso, observacoes
      ) VALUES (
        $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
        $11, $12, $13, $14, $15, $16, $17, $18, $19, $20,
        $21, $22
      ) RETURNING id;
    \`;
    
    const values = [
      data.foto, data.nome_completo, data.login, data.data_nascimento, data.estado_civil,
      data.nome_conjuge, data.data_casamento || null, data.telefone, data.email, data.cep,
      data.logradouro, data.bairro, data.cidade, data.uf, data.possui_veiculo,
      data.modelo_veiculo, data.paroquia, data.comunidade, data.setor, data.funcao,
      data.data_ingresso, data.observacoes
    ];

    const result = await client.query(query, values);
    console.log('   ✅ Cadastro realizado, ID:', result.rows[0].id);
    res.status(201).json({ success: true, id: result.rows[0].id });
    
  } catch (err) {
    console.error('❌ Erro no Cadastro:', err);
    res.status(500).json({ error: 'Erro ao salvar', details: err.message });
  } finally {
    if (client) client.release();
  }
});

// 4. Atualizar (PUT)
app.put('/api/membros/:id', async (req, res) => {
  console.log('👉 Atualizando membro ID:', req.params.id);
  let client;
  try {
    client = await pool.connect();
    const { id } = req.params;
    const data = req.body;
    
    const query = \`
      UPDATE membros SET
        foto = $1, nome_completo = $2, login = $3, data_nascimento = $4, estado_civil = $5,
        nome_conjuge = $6, data_casamento = $7, telefone = $8, email = $9, cep = $10,
        logradouro = $11, bairro = $12, cidade = $13, uf = $14, possui_veiculo = $15,
        modelo_veiculo = $16, paroquia = $17, comunidade = $18, setor = $19, funcao = $20,
        data_ingresso = $21, observacoes = $22
      WHERE id = $23
    \`;
    
    const values = [
      data.foto, data.nome_completo, data.login, data.data_nascimento, data.estado_civil,
      data.nome_conjuge, data.data_casamento || null, data.telefone, data.email, data.cep,
      data.logradouro, data.bairro, data.cidade, data.uf, data.possui_veiculo,
      data.modelo_veiculo, data.paroquia, data.comunidade, data.setor, data.funcao,
      data.data_ingresso, data.observacoes, id
    ];

    await client.query(query, values);
    console.log('   ✅ Atualizado com sucesso');
    res.json({ success: true });
    
  } catch (err) {
    console.error('❌ Erro na Atualização:', err);
    res.status(500).json({ error: 'Erro ao atualizar', details: err.message });
  } finally {
    if (client) client.release();
  }
});

// 5. Deletar (DELETE)
app.delete('/api/membros/:id', async (req, res) => {
  console.log('👉 Deletando membro ID:', req.params.id);
  let client;
  try {
    client = await pool.connect();
    const { id } = req.params;
    
    const query = 'DELETE FROM membros WHERE id = $1';
    await client.query(query, [id]);
    
    console.log('   ✅ Deletado com sucesso');
    res.json({ success: true });
    
  } catch (err) {
    console.error('❌ Erro ao deletar:', err);
    res.status(500).json({ error: 'Erro ao deletar', details: err.message });
  } finally {
    if (client) client.release();
  }
});

app.listen(port, '0.0.0.0', () => {
  console.log(\`🚀 Servidor rodando em http://localhost:\${port}\`);
});
`;

  return (
    <div className="p-6 h-full flex flex-col text-slate-100 animate-fade-in">
       {/* Header */}
       <div className="flex items-center justify-between mb-6">
        <div className="flex items-center gap-4">
          <button onClick={onBack} className="p-2 rounded-full bg-white/10 hover:bg-white/20 backdrop-blur text-white transition-all">
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15 19l-7-7 7-7" /></svg>
          </button>
          <h2 className="text-xl font-bold">Configuração do Servidor</h2>
        </div>
        <button 
           onClick={onNavigateToAI}
           className="text-xs text-blue-300 hover:text-white underline"
        >
          Precisa customizar?
        </button>
      </div>

      {/* Server Config Bar */}
      <div className="bg-blue-900/30 border border-blue-500/30 rounded-xl p-4 mb-6 flex flex-col gap-4">
        
        {showMixedContentWarning && (
            <div className="bg-orange-500/20 border border-orange-500/50 p-3 rounded text-orange-200 text-xs flex items-start gap-2">
                <svg className="w-5 h-5 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" /></svg>
                <div>
                    <strong>Atenção (Mixed Content):</strong> O navegador pode bloquear conexões HTTPS para HTTP local.
                    <br/>Solução: Use o Ngrok (aba 4) para criar um túnel seguro (https).
                </div>
            </div>
        )}

        <div className="flex flex-col md:flex-row items-center gap-4">
            <div className="flex items-center gap-3 w-full md:w-auto">
                <div className="p-2 bg-blue-500/20 rounded-full">
                    <svg className="w-5 h-5 text-blue-300" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 12h14M5 12a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v4a2 2 0 01-2 2M5 12a2 2 0 01-2 2v4a2 2 0 012 2h14a2 2 0 012-2v-4a2 2 0 01-2-2m-2-4h.01M17 16h.01" /></svg>
                </div>
                <div className="flex-1">
                    <label className="text-[10px] text-blue-300 uppercase font-bold tracking-wider block">Endereço do Servidor (API)</label>
                    {isEditingUrl ? (
                        <div className="flex items-center gap-2 mt-1">
                            <input 
                                type="text" 
                                value={tempUrl} 
                                onChange={(e) => setTempUrl(e.target.value)} 
                                className="bg-black/40 border border-blue-400 rounded px-2 py-1 text-sm text-white focus:outline-none w-full md:w-64"
                            />
                            <button onClick={handleSaveUrl} className="text-xs bg-green-600 hover:bg-green-500 text-white px-2 py-1 rounded">Salvar</button>
                            <button onClick={() => { setTempUrl(serverUrl); setIsEditingUrl(false); }} className="text-xs bg-slate-700 hover:bg-slate-600 text-white px-2 py-1 rounded">Cancelar</button>
                        </div>
                    ) : (
                        <div className="flex items-center gap-2 mt-1">
                            <span className="font-mono text-lg font-bold text-white">{serverUrl}</span>
                            <button onClick={() => setIsEditingUrl(true)} className="text-xs text-slate-400 hover:text-white" title="Editar IP">
                                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" /></svg>
                            </button>
                        </div>
                    )}
                </div>
            </div>
            
            <div className="h-8 w-[1px] bg-white/10 hidden md:block" />

            <div className="flex-1 w-full md:w-auto flex justify-end">
                <button 
                    onClick={handleTestConnection}
                    disabled={testing}
                    className={`w-full md:w-auto text-sm px-4 py-2 rounded-lg border transition-all flex items-center justify-center gap-2 font-semibold shadow-lg ${testing ? 'bg-yellow-500/20 border-yellow-500 text-yellow-200' : 'bg-green-500 hover:bg-green-400 text-white border-green-500/50'}`}
                >
                    {testing ? (
                        <>
                            <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-yellow-200"></div>
                            Verificando...
                        </>
                    ) : (
                        <>
                            Testar Conexão
                            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7" /></svg>
                        </>
                    )}
                </button>
            </div>
        </div>
    </div>

      {/* Tabs */}
      <div className="flex gap-2 mb-4 overflow-x-auto pb-2 md:pb-0">
        <button 
          onClick={() => setActiveTab('guide')}
          className={`flex-1 min-w-[120px] py-3 rounded-lg text-sm font-semibold transition-colors ${activeTab === 'guide' ? 'bg-indigo-600 text-white shadow-lg shadow-indigo-900/20' : 'bg-white/5 text-slate-400 hover:bg-white/10'}`}
        >
          1. Passo a Passo
        </button>
        <button 
          onClick={() => setActiveTab('sql')}
          className={`flex-1 min-w-[120px] py-3 rounded-lg text-sm font-semibold transition-colors ${activeTab === 'sql' ? 'bg-blue-600 text-white shadow-lg shadow-blue-900/20' : 'bg-white/5 text-slate-400 hover:bg-white/10'}`}
        >
          2. SQL Tabela
        </button>
        <button 
          onClick={() => setActiveTab('node')}
          className={`flex-1 min-w-[120px] py-3 rounded-lg text-sm font-semibold transition-colors ${activeTab === 'node' ? 'bg-green-600 text-white shadow-lg shadow-green-900/20' : 'bg-white/5 text-slate-400 hover:bg-white/10'}`}
        >
          3. Node.js API
        </button>
        <button 
          onClick={() => setActiveTab('ngrok')}
          className={`flex-1 min-w-[120px] py-3 rounded-lg text-sm font-semibold transition-colors ${activeTab === 'ngrok' ? 'bg-orange-600 text-white shadow-lg shadow-orange-900/20' : 'bg-white/5 text-slate-400 hover:bg-white/10'}`}
        >
          4. Ngrok (Vercel)
        </button>
      </div>

      {/* Code Area */}
      <div className="flex-1 relative bg-[#0d1117] rounded-xl border border-white/10 overflow-hidden flex flex-col shadow-inner">
        {activeTab === 'node' || activeTab === 'sql' ? (
            <div className="absolute top-0 right-0 p-3 z-10">
            <button 
                onClick={() => copyToClipboard(activeTab === 'node' ? nodeCode : sqlCode)}
                className="px-3 py-1.5 bg-white/10 hover:bg-white/20 rounded text-xs text-white border border-white/10 backdrop-blur transition-all active:scale-95 flex items-center gap-2"
            >
                {copied ? (
                    <>
                    <svg className="w-3 h-3 text-green-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7" /></svg>
                    Copiado!
                    </>
                ) : (
                    <>
                    <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M8 5H6a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2v-1M8 5a2 2 0 002 2h2a2 2 0 002-2M8 5a2 2 0 012-2h2a2 2 0 012 2m0 0h2a2 2 0 012 2v3m2 4H10m0 0l3-3m-3 3l3 3" /></svg>
                    Copiar
                    </>
                )}
            </button>
            </div>
        ) : null}
        
        <div className="flex-1 overflow-auto custom-scrollbar p-6">
            {activeTab === 'guide' && (
                <div className="space-y-8 text-sm text-slate-300">
                    
                    {/* TROUBLESHOOTING SECTION */}
                    <div className="bg-red-900/10 border border-red-500/20 p-4 rounded-lg">
                        <h3 className="text-red-300 font-bold text-lg mb-2 flex items-center gap-2">
                           ⚠️ IMPORTANTE: Atualize o arquivo server.js
                        </h3>
                        <p className="mb-2">Para habilitar o controle de permissões (Agente vê apenas a si mesmo), atualize seu código:</p>
                        <ol className="list-decimal pl-5 space-y-2 text-white">
                            <li>Clique na aba <strong className="text-green-300">3. Node.js API</strong> acima.</li>
                            <li>Copie o novo código (v8).</li>
                            <li>No seu PC, substitua todo o conteúdo do arquivo <code className="text-green-300">server.js</code>.</li>
                            <li>Reinicie o servidor (<code className="text-green-300">Ctrl+C</code> e depois <code className="text-green-300">node server.js</code>).</li>
                        </ol>
                    </div>

                    <div className="space-y-3">
                        <h3 className="text-blue-300 font-bold text-lg border-b border-white/10 pb-1">Passo A: Descobrir seu IP Real</h3>
                        <p>No terminal do Windows:</p>
                        <code className="block bg-black/40 p-3 rounded border border-white/5 font-mono text-green-400">
                            ipconfig
                        </code>
                        <p>Copie o <strong>IPv4</strong> e cole no campo acima (se não for usar Ngrok).</p>
                    </div>
                </div>
            )}

            {activeTab === 'ngrok' && (
                <div className="space-y-6 text-sm text-slate-300">
                     <div className="bg-orange-900/20 border border-orange-500/20 p-4 rounded-lg">
                        <h3 className="text-orange-300 font-bold text-lg mb-2">Solução Definitiva (Ngrok)</h3>
                        <p>Use o Ngrok para criar um endereço HTTPS seguro para seu servidor local. Isso resolve erros de "Mixed Content" e bloqueios do Vercel.</p>
                    </div>

                    <ol className="list-decimal pl-5 space-y-4">
                        <li>
                            Baixe o Ngrok em <a href="https://ngrok.com/download" target="_blank" className="text-blue-400 underline">ngrok.com</a> e instale.
                        </li>
                        <li>
                            No terminal, inicie o túnel:
                            <code className="block bg-black/40 p-3 rounded border border-white/5 font-mono text-green-400 mt-2">
                                ngrok http 3000
                            </code>
                        </li>
                        <li>
                            Copie o link <code className="text-white">https://....ngrok-free.app</code> e cole no campo "Endereço do Servidor" no topo desta tela.
                        </li>
                    </ol>
                </div>
            )}

            {activeTab === 'node' && (
                <pre className="text-xs md:text-sm font-mono text-blue-100 leading-relaxed">
                    <code>{nodeCode}</code>
                </pre>
            )}

            {activeTab === 'sql' && (
                <pre className="text-xs md:text-sm font-mono text-blue-100 leading-relaxed">
                    <code>{sqlCode}</code>
                </pre>
            )}
        </div>
      </div>
    </div>
  );
};
