
import React, { useState } from 'react';
import { LogType } from '../types';

interface ServerSetupProps {
  onBack: () => void;
  onNavigateToAI: () => void;
  addLog: (type: LogType, message: string, details?: string) => void;
  serverUrl: string;
  onUpdateServerUrl: (newUrl: string) => void;
}

export const ServerSetup: React.FC<ServerSetupProps> = ({ onBack, onNavigateToAI, addLog, serverUrl, onUpdateServerUrl }) => {
  const [activeTab, setActiveTab] = useState<'node' | 'sql' | 'guide'>('guide');
  const [copied, setCopied] = useState(false);
  const [testing, setTesting] = useState(false);
  const [isEditingUrl, setIsEditingUrl] = useState(false);
  const [tempUrl, setTempUrl] = useState(serverUrl);

  const isHttps = window.location.protocol === 'https:';
  const targetIsHttp = tempUrl.startsWith('http:');
  const showMixedContentWarning = isHttps && targetIsHttp;

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleTestConnection = async () => {
      setTesting(true);
      const urlToTest = serverUrl.replace(/\/$/, ''); // Remove trailing slash
      addLog('info', 'Tentando conectar ao backend...', `GET ${urlToTest}/`);
      
      try {
          const controller = new AbortController();
          const timeoutId = setTimeout(() => controller.abort(), 5000); // 5s timeout
          
          const response = await fetch(`${urlToTest}/`, { 
              signal: controller.signal,
              mode: 'cors' 
          });
          clearTimeout(timeoutId);

          if (response.ok) {
              const text = await response.text();
              addLog('success', 'Conexão Estabelecida!', `Resposta: ${text}`);
              alert("Sucesso! Conexão estabelecida com o servidor.");
          } else {
              addLog('warning', 'Servidor encontrado, mas retornou erro.', `Status: ${response.status}`);
          }
      } catch (error) {
           const err = error instanceof Error ? error.message : String(error);
           if (err.includes('aborted')) {
               addLog('error', 'Timeout: Servidor demorou para responder.', `Verifique o IP ${urlToTest} e a porta 3000.`);
           } else if (err.includes('Failed to fetch')) {
               addLog('error', 'Bloqueio de Rede ou CORS.', `O navegador bloqueou a conexão. Atualize o código do server.js (aba 3) e reinicie o Node.`);
           } else {
               addLog('error', 'Falha na conexão.', err);
           }
      } finally {
          setTesting(false);
      }
  };

  const handleSaveUrl = () => {
      onUpdateServerUrl(tempUrl);
      setIsEditingUrl(false);
  };

  const sqlCode = `
-- Conecte-se ao seu PostgreSQL e execute:
-- 1. Criação do Banco (Opcional se já tiver)
-- CREATE DATABASE pastoral_db;

-- 2. Conecte no banco e crie a tabela:
CREATE TABLE IF NOT EXISTS membros (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  foto TEXT,
  nome_completo TEXT NOT NULL,
  login TEXT NOT NULL UNIQUE,
  data_nascimento DATE NOT NULL,
  estado_civil TEXT NOT NULL,
  nome_conjuge TEXT,
  data_casamento DATE,
  telefone TEXT NOT NULL,
  email TEXT NOT NULL,
  cep TEXT NOT NULL,
  logradouro TEXT NOT NULL,
  bairro TEXT NOT NULL,
  cidade TEXT NOT NULL,
  uf TEXT NOT NULL,
  possui_veiculo BOOLEAN NOT NULL DEFAULT false,
  modelo_veiculo TEXT,
  paroquia TEXT NOT NULL,
  comunidade TEXT NOT NULL,
  setor TEXT NOT NULL,
  funcao TEXT NOT NULL,
  data_ingresso DATE NOT NULL DEFAULT CURRENT_DATE,
  observacoes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
`;

  const nodeCode = `
// server.js - Backend Atualizado para Pastoral
// Instale: npm install express pg cors helmet dotenv

require('dotenv').config();
const express = require('express');
const { Pool } = require('pg');
const cors = require('cors');
const helmet = require('helmet');

const app = express();
const port = process.env.PORT || 3000;

// Configuração CRÍTICA para funcionar em Rede Local (CORS + Private Network)
app.use(cors({
  origin: '*', // Em produção, restrinja para a URL do seu site
  methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS'],
  allowedHeaders: ['Content-Type', 'Authorization', 'Access-Control-Allow-Private-Network'],
  credentials: true
}));

// Middleware extra para permitir acesso de IP privado (Chrome/Edge update)
app.use((req, res, next) => {
  res.header("Access-Control-Allow-Private-Network", "true");
  next();
});

app.use(helmet());
app.use(express.json({ limit: '10mb' }));

// Conexão com Banco de Dados Doméstico
const pool = new Pool({
  user: process.env.DB_USER || 'postgres',
  host: process.env.DB_HOST || 'localhost',
  database: process.env.DB_NAME || 'pastoral_db',
  password: process.env.DB_PASSWORD || 'sua_senha_aqui',
  port: process.env.DB_PORT || 5432,
});

// GET: Rota de Teste Simples
app.get('/', (req, res) => res.send('API Pastoral Online ✝️'));

// GET: Listar Agentes
app.get('/api/membros', async (req, res) => {
  const client = await pool.connect();
  try {
    const result = await client.query('SELECT * FROM membros ORDER BY created_at DESC');
    res.json(result.rows);
  } catch (err) {
    res.status(500).json({ error: err.message });
  } finally {
    client.release();
  }
});

// POST: Criar novo Agente
app.post('/api/membros', async (req, res) => {
  const client = await pool.connect();
  try {
    const data = req.body;
    
    const query = \`
      INSERT INTO membros (
        foto, nome_completo, login, data_nascimento, estado_civil,
        nome_conjuge, data_casamento, telefone, email, cep,
        logradouro, bairro, cidade, uf, possui_veiculo,
        modelo_veiculo, paroquia, comunidade, setor, funcao,
        data_ingresso, observacoes
      ) VALUES (
        $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
        $11, $12, $13, $14, $15, $16, $17, $18, $19, $20,
        $21, $22
      ) RETURNING id;
    \`;

    const values = [
      data.foto, data.nome_completo, data.login, data.data_nascimento, data.estado_civil,
      data.nome_conjuge, data.data_casamento || null, data.telefone, data.email, data.cep,
      data.logradouro, data.bairro, data.cidade, data.uf, data.possui_veiculo,
      data.modelo_veiculo, data.paroquia, data.comunidade, data.setor, data.funcao,
      data.data_ingresso, data.observacoes
    ];

    const result = await client.query(query, values);
    res.status(201).json({ success: true, id: result.rows[0].id });

  } catch (err) {
    console.error('Erro ao cadastrar agente:', err);
    res.status(500).json({ error: 'Erro interno', details: err.message });
  } finally {
    client.release();
  }
});

// Escuta em todas as interfaces (0.0.0.0)
app.listen(port, '0.0.0.0', () => {
  console.log(\`Servidor rodando na porta \${port}\`);
  console.log(\`Acesse: http://\${require('os').hostname()}:\${port}\`);
});
`;

  return (
    <div className="p-6 h-full flex flex-col text-slate-100 animate-fade-in">
       {/* Header */}
       <div className="flex items-center justify-between mb-6">
        <div className="flex items-center gap-4">
          <button onClick={onBack} className="p-2 rounded-full bg-white/10 hover:bg-white/20 backdrop-blur text-white transition-all">
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15 19l-7-7 7-7" /></svg>
          </button>
          <h2 className="text-xl font-bold">Configuração do Servidor</h2>
        </div>
        <button 
           onClick={onNavigateToAI}
           className="text-xs text-blue-300 hover:text-white underline"
        >
          Precisa customizar?
        </button>
      </div>

      {/* Server Config Bar */}
      <div className="bg-blue-900/30 border border-blue-500/30 rounded-xl p-4 mb-6 flex flex-col gap-4">
        
        {showMixedContentWarning && (
            <div className="bg-orange-500/20 border border-orange-500/50 p-3 rounded text-orange-200 text-xs flex items-start gap-2">
                <svg className="w-5 h-5 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" /></svg>
                <div>
                    <strong>Atenção (Mixed Content):</strong> Você está acessando este site via <strong>HTTPS</strong>, mas tentando conectar num servidor <strong>HTTP</strong>. O navegador bloqueará isso por segurança.
                    <br/>Solução: Acesse este site via HTTP (se for local) ou instale um túnel seguro (Cloudflare) no seu servidor.
                </div>
            </div>
        )}

        <div className="flex flex-col md:flex-row items-center gap-4">
            <div className="flex items-center gap-3 w-full md:w-auto">
                <div className="p-2 bg-blue-500/20 rounded-full">
                    <svg className="w-5 h-5 text-blue-300" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 12h14M5 12a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v4a2 2 0 01-2 2M5 12a2 2 0 01-2 2v4a2 2 0 012 2h14a2 2 0 012-2v-4a2 2 0 01-2-2m-2-4h.01M17 16h.01" /></svg>
                </div>
                <div className="flex-1">
                    <label className="text-[10px] text-blue-300 uppercase font-bold tracking-wider block">Endereço do Servidor (API)</label>
                    {isEditingUrl ? (
                        <div className="flex items-center gap-2 mt-1">
                            <input 
                                type="text" 
                                value={tempUrl} 
                                onChange={(e) => setTempUrl(e.target.value)} 
                                className="bg-black/40 border border-blue-400 rounded px-2 py-1 text-sm text-white focus:outline-none w-full md:w-64"
                            />
                            <button onClick={handleSaveUrl} className="text-xs bg-green-600 hover:bg-green-500 text-white px-2 py-1 rounded">Salvar</button>
                            <button onClick={() => { setTempUrl(serverUrl); setIsEditingUrl(false); }} className="text-xs bg-slate-700 hover:bg-slate-600 text-white px-2 py-1 rounded">Cancelar</button>
                        </div>
                    ) : (
                        <div className="flex items-center gap-2 mt-1">
                            <span className="font-mono text-lg font-bold text-white">{serverUrl}</span>
                            <button onClick={() => setIsEditingUrl(true)} className="text-xs text-slate-400 hover:text-white" title="Editar IP">
                                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" /></svg>
                            </button>
                        </div>
                    )}
                </div>
            </div>
            
            <div className="h-8 w-[1px] bg-white/10 hidden md:block" />

            <div className="flex-1 w-full md:w-auto flex justify-end">
                <button 
                    onClick={handleTestConnection}
                    disabled={testing}
                    className={`w-full md:w-auto text-sm px-4 py-2 rounded-lg border transition-all flex items-center justify-center gap-2 font-semibold shadow-lg ${testing ? 'bg-yellow-500/20 border-yellow-500 text-yellow-200' : 'bg-green-500 hover:bg-green-400 text-white border-green-500/50'}`}
                >
                    {testing ? (
                        <>
                            <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-yellow-200"></div>
                            Verificando...
                        </>
                    ) : (
                        <>
                            Testar Conexão
                            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7" /></svg>
                        </>
                    )}
                </button>
            </div>
        </div>
      </div>

      {/* Tabs */}
      <div className="flex gap-2 mb-4 overflow-x-auto pb-2 md:pb-0">
        <button 
          onClick={() => setActiveTab('guide')}
          className={`flex-1 min-w-[120px] py-3 rounded-lg text-sm font-semibold transition-colors ${activeTab === 'guide' ? 'bg-indigo-600 text-white shadow-lg shadow-indigo-900/20' : 'bg-white/5 text-slate-400 hover:bg-white/10'}`}
        >
          1. Passo a Passo
        </button>
        <button 
          onClick={() => setActiveTab('sql')}
          className={`flex-1 min-w-[120px] py-3 rounded-lg text-sm font-semibold transition-colors ${activeTab === 'sql' ? 'bg-blue-600 text-white shadow-lg shadow-blue-900/20' : 'bg-white/5 text-slate-400 hover:bg-white/10'}`}
        >
          2. SQL Tabela
        </button>
        <button 
          onClick={() => setActiveTab('node')}
          className={`flex-1 min-w-[120px] py-3 rounded-lg text-sm font-semibold transition-colors ${activeTab === 'node' ? 'bg-green-600 text-white shadow-lg shadow-green-900/20' : 'bg-white/5 text-slate-400 hover:bg-white/10'}`}
        >
          3. Node.js API
        </button>
      </div>

      {/* Code Area */}
      <div className="flex-1 relative bg-[#0d1117] rounded-xl border border-white/10 overflow-hidden flex flex-col shadow-inner">
        {activeTab !== 'guide' && (
            <div className="absolute top-0 right-0 p-3 z-10">
            <button 
                onClick={() => copyToClipboard(activeTab === 'node' ? nodeCode : sqlCode)}
                className="px-3 py-1.5 bg-white/10 hover:bg-white/20 rounded text-xs text-white border border-white/10 backdrop-blur transition-all active:scale-95 flex items-center gap-2"
            >
                {copied ? (
                    <>
                    <svg className="w-3 h-3 text-green-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7" /></svg>
                    Copiado!
                    </>
                ) : (
                    <>
                    <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M8 5H6a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2v-1M8 5a2 2 0 002 2h2a2 2 0 002-2M8 5a2 2 0 012-2h2a2 2 0 012 2m0 0h2a2 2 0 012 2v3m2 4H10m0 0l3-3m-3 3l3 3" /></svg>
                    Copiar
                    </>
                )}
            </button>
            </div>
        )}
        
        <div className="flex-1 overflow-auto custom-scrollbar p-6">
            {activeTab === 'guide' && (
                <div className="space-y-8 text-sm text-slate-300">
                    
                    {/* TROUBLESHOOTING SECTION */}
                    <div className="bg-red-900/10 border border-red-500/20 p-4 rounded-lg">
                        <h3 className="text-red-300 font-bold text-lg mb-2 flex items-center gap-2">
                           ⚠️ Problemas de Conexão? Leia aqui.
                        </h3>
                        <p className="mb-2">Se o "Teste de Conexão" falhou, geralmente é por um destes dois motivos:</p>
                        <ul className="list-disc pl-5 space-y-2">
                            <li>
                                <strong className="text-white">IP Incorreto:</strong> Seu roteador pode ter mudado o IP do servidor.
                            </li>
                            <li>
                                <strong className="text-white">Firewall do Windows:</strong> O Windows bloqueia a porta 3000 por padrão.
                            </li>
                            <li>
                                <strong className="text-white">Bloqueio de Navegador (CORS):</strong> Atualize o <code className="text-green-300">server.js</code> com o código da aba 3, que agora inclui o desbloqueio <i>"Access-Control-Allow-Private-Network"</i>.
                            </li>
                        </ul>
                    </div>

                    <div className="space-y-3">
                        <h3 className="text-blue-300 font-bold text-lg border-b border-white/10 pb-1">Passo A: Descobrir seu IP Real</h3>
                        <p>No computador onde o Node.js vai rodar, abra o terminal (Prompt de Comando ou PowerShell) e digite:</p>
                        <code className="block bg-black/40 p-3 rounded border border-white/5 font-mono text-green-400">
                            ipconfig
                        </code>
                        <p>Procure por <strong>Endereço IPv4</strong>. Ele deve ser algo como <code className="text-yellow-200">192.168.x.x</code> ou <code className="text-yellow-200">10.0.x.x</code>. <br/>Insira esse número no campo de edição acima.</p>
                    </div>

                    <div className="space-y-3">
                         <h3 className="text-blue-300 font-bold text-lg border-b border-white/10 pb-1">Passo B: Liberar o Firewall</h3>
                         <p>Para permitir que outros dispositivos acessem seu servidor, você precisa abrir a porta 3000. Rode este comando no <strong>PowerShell como Administrador</strong>:</p>
                         <code className="block bg-black/40 p-3 rounded border border-white/5 font-mono text-green-400 select-all">
                             New-NetFirewallRule -DisplayName "NodeJS Pastoral" -Direction Inbound -LocalPort 3000 -Protocol TCP -Action Allow
                         </code>
                    </div>

                    <div className="space-y-3">
                        <h3 className="text-blue-300 font-bold text-lg border-b border-white/10 pb-1">Passo C: Instalar e Rodar</h3>
                        <p>1. Crie a pasta e instale as dependências:</p>
                        <code className="block bg-black/40 p-3 rounded border border-white/5 font-mono text-slate-400">
                            mkdir backend-pastoral<br/>
                            cd backend-pastoral<br/>
                            npm init -y<br/>
                            npm install express pg cors helmet dotenv
                        </code>
                        <p>2. Crie o arquivo <code className="text-white">server.js</code> (código na aba 3) e o arquivo <code className="text-white">.env</code>.</p>
                        <p>3. Rode o servidor:</p>
                        <code className="block bg-black/40 p-3 rounded border border-white/5 font-mono text-green-400">
                            node server.js
                        </code>
                    </div>
                </div>
            )}

            {activeTab === 'node' && (
                <pre className="text-xs md:text-sm font-mono text-blue-100 leading-relaxed">
                    <code>{nodeCode}</code>
                </pre>
            )}

            {activeTab === 'sql' && (
                <pre className="text-xs md:text-sm font-mono text-blue-100 leading-relaxed">
                    <code>{sqlCode}</code>
                </pre>
            )}
        </div>
      </div>
    </div>
  );
};
